# 配置版本，请勿编辑
version: 3

#设置多久更新一次计分板中的内容，单位ticks (20 ticks = 1秒)
#0=默认值，禁止更新计分板内容，若你使用PlaceholderAPI插件就必须设置一个数字！
update: 0

#使用异步更新（多线程）
#开启后可以减少计分板更新内容造成的卡顿
async: true

#计分板标题
title: "§eSimple§9Scoreboards"

#计分板标题
#你可以使用§为颜色和Placeholders，来自PlaceholderAPI
text:
  - "§d版本§5${pom.version}"
  - "§a作者:§3PetteriM1"
  - "§6在配置文件中设置计分板内容"

#禁用计分板的世界列表
noScoreboardWorlds:
  - "exampleWorld"
